### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by muminoff** [lukasschwab/stackit#11]
Why stackit when there is already [howdoi](https://github.com/gleitz/howdoi)?

**Comment by lukasschwab** [comment]
Looking at the howdoi documentation, I think they offer different functionality.

`stackit` specifically targets the debugging process, especially with the `-e` command line argument, whereas `howdoi` seems to work really well for answering simple questions before you write code. `stackit` functions as a CLI for StackOverflow, whereas `howdoi` returns single answers.

Closing b/c not actually an issue––happy to continue discussion on closed thread.
